### ISSUE TITLE
AttributeError: module 'click' has no attribute 'FloatRange'

### ISSUE THREAD

**Issue by islamzee** [All-less/trace-generator#1]
After installing package either with pip3 or pip, running the generation command without any options gives the error:

> Traceback (most recent call last):
>   File "/Users/zeenat/anaconda3/bin/spar", line 5, in <module>
>     from spar.cli import main
>   File "/Users/zeenat/anaconda3/lib/python3.6/site-packages/spar/cli.py", line 20, in <module>
>     @click.option('--duration', type=click.FloatRange(0, None), default=1,
> AttributeError: module 'click' has no attribute 'FloatRange'

Command was: spar <OUTPUT_DIR>

**Comment by All-less** [comment]
I suspect that your `click` package is outdated, so could you check the version?
```
pip3 show click
```
If the version is lower than 7.0, you may update it with
```
pip3 install --upgrade click==7.0
```

**Comment by islamzee** [comment]
Thanks for the fix! That worked.
But the option --output-dir does not work.

![image](https://user-images.githubusercontent.com/10813512/72209085-f23cbf80-34d4-11ea-8583-3ace60375e76.png)

**Comment by All-less** [comment]
Thanks for pointing it out. Actually '--output-dir' has been changed from an option to an argument, which means you don't have to specify the flag name anymore. I have updated the package and the readme accordingly. Please check it out.
